### ISSUE TITLE
安装失败，安装有顺序要求吗？

### ISSUE THREAD

**Issue by woaigithub** [vfasky/BlogCatke#1]
我是先初始化mysql，然后初始化memcache，然后初始化storage，然后上传带代码，都成功了。
但是访问/install没有提示安装，请问？

**Comment by woaigithub** [comment]
cloudpyblog.sinapp.com/install
超时失败了

**Comment by woaigithub** [comment]
数据库表是自动建立吗？还是需要我导入sql手动建立呢？

**Comment by woaigithub** [comment]
现在可以了，看来需要等一会的，心急了，谢谢！@

**Comment by vfasky** [comment]
1. ص1.0.1 Դ?
   1.0 İװ,,鷳°   (
   http://qcoreblog.sinaapp.com/post/QcoreBlog-setup-help.html )
2. ûȺ˳, °Դ, ܷṩ /install Ľͼ
   
   201223 7:50woaigithub <
   reply@reply.github.com
