### ISSUE TITLE
后台撰写文章页面小建议

### ISSUE THREAD

**Issue by glfeng318** [vfasky/BlogCatke#2]
`发表`那个按钮如果放在编辑框跟跟预览之间，或者直接放到右边，我感觉会方便点，编辑长文的时候，得拼命下拉找这个按钮。
我相当喜欢这个东西：够简单、使用markdown。希望可以保持下去。

**Comment by vfasky** [comment]
非常感谢你的建议,下一版会修改.

**Comment by vfasky** [comment]
fix bug
